### ISSUE TITLE
Difference between Opacity and Blur

### ISSUE THREAD

**Issue by tujoworker** [kosso/TiTranslucentView#1]
Thanks for making this module!

But theres something I have to discuss about.
I can't se de difference between the view with the module and a custom generated view with a backgroundColor like that:

```
backgroundColor:'#05ffffff',
```

What is the difference?
- I have tested this on both the simulator and my device with iOS 7.1.4

**Comment by kosso** [comment]
It's not the best module. Not all things work as expected,

But what color is '#05ffffff' supposed to be?? That's not a real colour. #RRGGBB

**Comment by tujoworker** [comment]
#05ffffff is like rgba(255,255,255,0.5)
#00ffffff = 0.0 opacity
#99ffffff = 1.0 opacity

I think.
But you can use the RRGGBB color of your choice. I like this better than rgba.
Anyway, hope you find the problems with the blur, cause to me it looks like it's all about the blur to get work.

**Comment by kosso** [comment]
Nope. That's not how to do transparency.  If you need to, use the 'opacity' property. 

ps: There are probably better modules out there to do this effect.

**Comment by tujoworker** [comment]
Sorry, but this works in Titanium.
I like this better than rgba.

## 

This email was sent on the road.

**Comment by kosso** [comment]
I take back what I said. You're right. That does do transparency. Wow. I never knew that hex way before.  ;) 

I haven't looked at this module in a while. I think there are plenty of others out there now.
